### ISSUE TITLE
Client Updates for v2ray vmess support

### ISSUE THREAD

**Issue by miyorineko** [blinksocks/blinksocks-desktop#22]
The blinksocks core supported vmess already, but is there any updates for the client here? (I've also noticed the last commit to the client repository is 2 months ago. I wonder if the desktop client is obsoleted?)

**Comment by micooz** [comment]
Sorry for not keep working on this repo :(

It took me a lot of time since I created it, I want to make it cross-platform, easy to distribute and as small as possible, but it doesn't seem lightweight enough, thus, blinksocks core comes with a portable version(also cross-platform) which doesn't require any dependencies or frameworks to be installed first.

I'll keep contributing to the core library and there are plenty of new features to be done in the next few months :)

BTW, If anyone can take over or maintain this project, I'll be very glad.

**Comment by micooz** [comment]
We've just released a web based GUI named [blinksocks-gui](https://github.com/blinksocks/blinksocks-gui) to take place of `blinksocks-desktop`, try it at 
https://gui.blinksocks.org/landing?password=preview
